-- MySQL Script generated by MySQL Workbench
-- Fri Sep  3 17:15:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema desafio_leo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafio_leo` DEFAULT CHARACTER SET utf8 ;
USE `desafio_leo` ;

-- -----------------------------------------------------
-- Table `desafio_leo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio_leo`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  `img` VARCHAR(255) NULL,
  `modal` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_leo`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio_leo`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img` VARCHAR(255) NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  `slideshow` VARCHAR(255) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_cursos_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `desafio_leo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
